jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: 'npm i -g npm@6.10.0'
        displayName: 'Change npm version'
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file vscode-extension-di'
        workingDirectory: vscode-extension-di
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file'
        workingDirectory: vscode-spring-cloud-dataflow
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'run compile'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'test'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: 'npm i -g npm@6.10.0'
        displayName: 'Change npm version'
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file vscode-extension-di'
        workingDirectory: vscode-extension-di
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file'
        workingDirectory: vscode-spring-cloud-dataflow
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'run compile'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'test'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: 'npm i -g npm@6.10.0'
        displayName: 'Change npm version'
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-core'
        inputs:
          workingDir: vscode-extension-core
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file vscode-extension-di'
        workingDirectory: vscode-extension-di
      - task: Npm@1
        displayName: 'Install dependencies vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          verbose: false
      - task: Npm@1
        displayName: 'Pack vscode-extension-di'
        inputs:
          workingDir: vscode-extension-di
          command: custom
          verbose: false
          customCommand: 'pack'
      - script: 'rm package-lock.json'
        displayName: 'Delete lock file'
        workingDirectory: vscode-spring-cloud-dataflow
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'run compile'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - task: Npm@1
        displayName: 'Run tests'
        env:
          DISPLAY: :10
        inputs:
          workingDir: vscode-spring-cloud-dataflow
          command: custom
          verbose: false
          customCommand: 'test'
