logging:
  level:
    org.springframework.dsl: debug
    org.springframework.cloud.dataflow.language.server: debug
spring:
  main:
    banner-mode: "off"
  autoconfigure:
    exclude: org.springframework.cloud.dataflow.rest.client.config.DataFlowClientAutoConfiguration
  dsl:
    lsp:
      server:
        mode: PROCESS
